Fix failed TestDependencyVersionsConsistent test
When dpkg-source unpack tarball, it produces .pc dir in source dir.
The last patch 0007-CVE-2021-31525.patch causes
go.mod/go.sum/modules.txt files in .pc dir with old content.
Then TestDependencyVersionsConsistent picks these old content in .pc
dir, results error:

--- FAIL: TestDependencyVersionsConsistent (0.00s)
    moddeps_test.go:217: Modules within GOROOT require different versions of golang.org/x/net.
    moddeps_test.go:229: std	requires v0.0.0-20201008223702-a5fa9d4b7c91
    moddeps_test.go:229: std	requires v0.0.0-20210428183841-261fb518b1ed