Apply debian/patches/0005-increase-size-limit-in-size-check.patch
From https://go-review.googlesource.com/c/go/+/371634:

    misc/cgo/testshared: increase size limit in size check

    Recently in Fedora we switched binutils ld's separate-code on. This
    led to increased size of binaries, especially on 64k aligned arches.
    For example trivial test binary size grew from 80k to 211k on ppc64le
    tripping the size check(RHBZ#2030308). Therefore adjusting the size limit.

Fixes FTBFS on ppc64el:

    ##### ../misc/cgo/testshared
    --- FAIL: TestTrivialExecutable (5.02s)
        shared_test.go:483: file too large: got 138376, want <= 100000
    --- FAIL: TestTrivialExecutablePIE (0.62s)
        shared_test.go:483: file too large: got 138376, want <= 100000
    FAIL
    FAIL	misc/cgo/testshared	57.857s
    FAIL
    2022/08/10 09:04:12 Failed: exit status 1